server:
  port: :8080

jwt:
  signkey: secret
  tokenTTL: 5m
  
db:
  host: localhost
  port: 5432
  user: postgres
  password: password
  dbname: shop
  sslmode: disable
  max_open_conn: 30
  max_idle_conn: 30
  max_idle_time: 15m
  
